### PR TITLE
port to newer mirage interfaces (-lwt/_lwt be gone)

### PR DESCRIPTION
**Pull request by hannesm**
//cc @djs55 @avsm

### CODE REVIEW

**Review by talex5 — APPROVED** [review]
LGTM, and since master is failing we should probably merge now.

Travis is being slow though. Perhaps remove it? It looks like the Travis tests are just a subset of the ocaml-ci ones.

**Comment by hannesm** [comment]
I'm fine removing travis, though I don't feel in charge of this repository (and would appreciate someone else to decide whether removing travis is ok). I enabled OCaml-CI earlier on this repository to get quick feedback.

**Comment by avsm** [comment]
With ocaml-ci's current maturity, I'm fine with removing Travis on all of the mirage/ repositories.

**Comment by hannesm** [comment]
cool, would you cut a release to opam-repository? :)

**Pull request merged**
