### PR TITLE
Test and fix create (fid should be rebound)

### PR DESCRIPTION
**Pull request by djs55**
When `create` succeeds, the fid should be rebound from the parent to the child.

### CODE REVIEW

**Comment by djs55** [comment]
Note the new unit test is unhooked because of #29

**Comment by djs55** [comment]
Hm, it seems the tests might block under other circumstances :(

**Comment by dsheets** [comment]
Ah, and now I see it doesn't matter. Thanks so much for changing the server shutdown procedure. This is a much nicer test harness. :-)

**Comment by djs55** [comment]
You're welcome. Sorry I led you on a bit of a wild goose chase with the earlier patches -- I hacked first and thought second ;-)

**Pull request merged**
