### PR TITLE
Prepare to release 0.7.0

### PR DESCRIPTION
**Pull request by djs55**

### CODE REVIEW

**Comment by talex5** [comment]
No fix for #85?

**Comment by djs55** [comment]
I've not got one -- is it something I can literally throw together in 15-20 minutes? :)

**Comment by talex5** [comment]
OK, no problem if it's hard to fix. Just checking it hadn't been missed.

**Comment by djs55** [comment]
How's that?

**Comment by djs55** [comment]
I think I'll merge this manually since github keeps losing half the patches (!)

**Pull request merged**
