### PR TITLE
Use Logs library for logging

### PR DESCRIPTION
**Pull request by talex5**
Testing @dbuenzli's new logging library...

e.g.

    $ ./main.native serve -v debug
    main.native: [INFO] Listening on 127.0.0.1 port 5640

### CODE REVIEW

**Comment by dsheets** [comment]
This adds a dependency that, I think, could have been opted into by clients via the previously parameterized `S.LOG` functor argument (maybe the `S.LOG` signature needs changing to allow that?). Also, does this allocate a closure for every logging expression even if logging has been disabled? I know @yallop was looking at some related stuff in the context of ocaml-git.

I guess I understand why you're playing with it but I don't know if it's an improvement.

**Comment by talex5** [comment]
I believe the current design is the result of @yallop's experiments. It seems this was the most efficient way.

The core Logs library is intended to be a very small dependency (https://github.com/dbuenzli/logs/blob/master/src/logs.ml) - small enough that projects shouldn't have to worry about adding it. The other parts (output to console, cmdliner support) are only dependencies for the example executable, not for the library.

We might be able to keep the log argument to the functors and avoid the dependency, though. I was trying to use the library as it seemed intended to be used. The functor approach would prevent us from later creating sub-loggers (9p-server, 9p-handler, 9p-wire, etc), unless the Log signature was extended to allow that. It might also be a problem if we want to support tags. Actually, I'm not sure if we can make a compatible signature, because e.g. `Logs.LOG.info`'s optional tags argument has the abstract type `Logs.Tag.set`.

**Comment by dsheets** [comment]
Hmm... ok. This is fine with me.

**Comment by dsheets** [comment]
I'd like to have a satisfactory solution for the singleton logger issue that would complicate #20 before this is merged. Perhaps naming connection contexts and emitting them in log messages?

**Comment by talex5** [comment]
Yes, I'm not happy with this patch either. I think we should keep the current functor-based design and just modify it to match the Logs signature, as you suggested.

(however, it would be possible to add the context as a tag in this case)

**Comment by djs55** [comment]
Slight snag -- I don't think v0.0.0 of the logs library is in opam yet

**Comment by talex5** [comment]
I've made a new attempt at adding logs support. This one is less invasive - it keeps the log functor arguments but changes the type signatures to be compatible with Logs. This means we still get annotations in the unit-test results, which now look like this:

```
DBG [client1] Successfully negotiated a connection.
DBG [client2] C ((tag ())
                 (payload (Version ((msize 8215) (version TwoThousandU)))))
DBG [server] accepted connection
DBG [server] C ((tag ())
                (payload (Version ((msize 8215) (version TwoThousandU)))))
DBG [server] S ((tag ())
                (payload (Version ((msize 8215) (version TwoThousandU)))))
INF [server] Using protocol TwoThousandU msize 8215
DBG [client2] S ((tag ())
                 (payload (Version ((msize 8215) (version TwoThousandU)))))
DBG [client2] Negotiated maximum message size: 8215 bytes
```

My motivation for this is that it should let us compile with verbose logging of all traffic by default, since logs doesn't make us pay the cost of formatting a message if it won't be used.

**Comment by djs55** [comment]
Let's do this!

**Pull request merged**
