### PR TITLE
Remove oasis, remove -pack

### PR DESCRIPTION
**Pull request by dsheets**
This patch introduces a lot of changes to the build system and related areas.

Among the changes are:

 - Rewrite build system to use only `make` and `ocamlbuild`
 - Remove use of `-pack` and use module aliases instead
 - Use symlinks to keep similar files the same (e.g. `.mllib` and `.mldylib` and modules with `.mli` but no `.ml`)
 - Change CHANGES format to use ISO dates and look more like other Mirage change logs
 - Begin using revision versions in version numbers
 - Use full module names in module signatures internally
 - Introduce short aliases for module implementations internally
 - Improve adherence to 80 character column convention

### CODE REVIEW

**Comment by dsheets** [comment]
Oh, I should also say that the realization that `Protocol_9p.Response.sizeof_header` and `Protocol_9p.Response.Read.sizeof_header` were hidden is what prompted this.

**Comment by dsheets** [comment]
Something's broken with the coverage checking? I have no idea how that works.

**Comment by dsheets** [comment]
Gah, I missed out some archives, one sec.

**Comment by dsheets** [comment]
@djs55 I think this is ready if you're comfortable with it.

**Comment by djs55** [comment]
The tests passed but coverage checking failed -- it needs a bit more build integration. No need to hold up this merge though :shipit:

**Pull request merged**
