### PR TITLE
lofs fid improvements

### PR DESCRIPTION
**Pull request by djs55**
- walk should fail if the newfid is in use (if it is not the same as fid)
- remove should clunk the fid in the failure case
- associate open fid with file or directory handles
- `read` and `write` of a closed fid now return `bad fid`
- handle out-of-bounds directory reading a bit better

### CODE REVIEW

**Comment by djs55** [comment]
@dsheets this is my first cut of associating handles with fids. Let me know what you think.

In the case I'm most concerned about today I don't know if this is a good enough fix. If I open a directory (`opendir`) and cache the `dir_handle`, and then on every `read` I do a `with_mutex (rewinddir; readdir)`, will I see the contents changing if someone removes a file from the directory? I wonder if I need to actively snapshot the directory contents?

**Comment by djs55** [comment]
Hm I seem to have broken the protocol negotiation with Linux :/

**Comment by dsheets** [comment]
Cool! Great that `rm -rf` works now.

**Comment by djs55** [comment]
Thanks for the feedback. I've incorporated everything except I still need to rewrite the `readdir` use along the lines you suggested-- for expediency I'll probably make that one an issue and merge this PR since it makes things work a lot better with Linux.

**Pull request merged**
